language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - yarn --frozen-lockfile
script:
  - npm ci
  - npx jest --ci
